home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'home'

urlpatterns = [
    path('delete_<int:pk>/', views.postDelete, name='postDelete'),
    path('edit_list_<int:pk>/', views.postEdit, name='postEdit'),
    path('add_list/', views.postCreate, name='postCreate'),
    path('check_details_<int:pk>/', views.PostDetail.as_view()),

    # 메인
    path('', views.PostList.as_view(), name='post_list'),
    # 카테고리 별
    path('category/<str:slug>/', views.category_page, name='category'),
    # 컴플리트(메인)
    path('todo_check/<int:pk>/', views.todo_check, name='todo_check'),
    # 컴플리트(카테고리)
    path('category/<str:slug>/todo_check_category/<int:pk>/', views.todo_check_category, name='todo_check_category'),
    path('category/no_category/<int:pk>/', views.todo_check_no_category, name='todo_check_no_category'),
    # 날짜 넘기기
    path('change_date/', views.change_date, name='change_date'),
    # 컴플리트(상세확인)
    path('todo_check2/<int:pk>/', views.todo_check2, name='todo_check2'),

    # 마이
    path('my/', views.my),

    # 팝업창
    path('popup/', views.popup),

    ]

toDD_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('eclass/', include('eclass.urls')),
    path('alarm/', include('alarm.urls')),
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.contrib.auth.models import User
from django.db import models

import os
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/home/category/{self.slug}'


class Post(models.Model):
    # 투두 리스트 제목
    title = models.CharField(max_length=30)
    # 투두 리스트 상세 내용
    content = models.TextField()
    # 데드라인
    deadline = models.DateTimeField(auto_now=False)
    # 카테고리
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    # 완료 여부
    complete = models.BooleanField(default=False)
    # 리스트 만든 날짜
    created_at = models.DateTimeField(default=timezone.now, blank=True)
    # 유저
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)


    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'../../../home/check_details_{self.pk}/'

    def is_deadline_today(self):
        today = timezone.now()
        deadline = self.deadline

        difference = deadline - today

        return 0 <= difference.total_seconds() <= 86400 and not self.complete

home/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'deadline', 'category']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control border-0',
                    'style': 'background-color: #FFFFF4; max-length: 30;',
                    'placeholder': '제목 작성',
                }),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control border-0',
                    'cols': 70,
                    'rows': 8,
                    'style': 'background-color: #FFF7D3;',
                    'placeholder': '내용 작성'
                }),
            'deadline': forms.DateTimeInput(
                attrs={
                    'type': 'datetime-local',
                    'class': 'form-control border-0',
                    'style': 'background-color: #FFEC9D;',
                }),
            'category': forms.Select(
                attrs={
                    'class': 'form-control border-0',
                    'style': 'background-color: #FFEC9D;',
                }),
        }

home/views.py
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import ListView, DetailView
from .forms import PostForm
from .models import Post, Category
from eclass.models import Assignment, Quiz
from datetime import datetime, timedelta
from django.utils.dateformat import DateFormat
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
from collections import deque


def todo_check_category(request, pk, slug):
    category = get_object_or_404(Category, slug=slug)
    todo = get_object_or_404(Post, pk=pk)
    todo.complete = not todo.complete
    todo.save()
    return redirect('home:category', slug=category.slug)


def todo_check_no_category(request, pk):
    todo = get_object_or_404(Post, pk=pk, category=None)
    todo.complete = not todo.complete
    todo.save()
    return redirect('home:category', slug='no_category')


def todo_check2(request, pk):
    todo = get_object_or_404(Post, pk=pk)
    todo.complete = not todo.complete
    todo.save()
    return redirect(f'../../../home/check_details_{pk}/')


def category_page(request, slug):
    assignment = Assignment.objects.all()
    quiz = Quiz.objects.all()
    category = get_object_or_404(Category, slug='e_class')

    try:
        for other in assignment:
            Post.objects.get_or_create(
                title=str('[' + other.activity.lecture.name + ']') + other.title,
                content=other.content,
                deadline=other.due_date,
                category=category,
                author=request.user,
            )

        for other in quiz:
            Post.objects.get_or_create(
                title=str('[' + other.activity.lecture.name + ']') + other.title,
                content=other.questions,
                deadline=other.due_date,
                category=category,
                author=request.user,
            )
    except Post.MultipleObjectsReturned:
        pass

    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None, author=request.user)
    else:
        category = get_object_or_404(Category, slug=slug)
        post_list = Post.objects.filter(category=category, author=request.user)

    all_categories = Category.objects.all()
    categories_post_counts = {}
    for category_d in all_categories:
        count = Post.objects.filter(category=category_d, author=request.user).count()
        categories_post_counts[category_d] = count

    return render(
        request,
        'home/category_list.html',
        {
            'post_list': post_list,
            'no_categories_post_count': Post.objects.filter(category=None, author=request.user).count(),
            'category': category,
            'no_category_slug': 'no_category',
            'categories_post_counts': categories_post_counts,
        }
    )


def todo_check(request, pk):
    todo = get_object_or_404(Post, pk=pk)
    todo.complete = not todo.complete
    todo.save()

    # 현재 complete한 todo의 데드라인 날짜로 stored_date를 초기화
    stored_date = todo.deadline.date().strftime('%Y-%m-%d')
    request.session['stored_date'] = stored_date
    print("Updated stored_date:", request.session['stored_date'])
    stored_date_str = request.session['stored_date']

    stored_date = datetime.strptime(stored_date, '%Y-%m-%d').date()

    # 요일 설정
    dateDict = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}

    # 날짜 출력
    today_formatted = DateFormat(stored_date).format('Y.m.d')
    today = today_formatted + ' (' + dateDict[stored_date.weekday()] + ')'

    post_list_today = Post.objects.filter(deadline__date=stored_date, author=request.user)

    all_categories = Category.objects.all()

    categories_post_counts = {}
    for category in all_categories:
        count = Post.objects.filter(category=category, author=request.user).count()
        categories_post_counts[category] = count

    no_categories_post_count = Post.objects.filter(category=None, author=request.user).count()

    return render(
        request,
        'home/post_list.html',
        {
            'post_list_today': post_list_today,
            'stored_date_str': stored_date_str,
            'today': today,
            'stored_date': stored_date.strftime('%Y-%m-%d'),
            'no_categories_post_count': no_categories_post_count,
            'categories_post_counts': categories_post_counts,
        }
    )


class PostList(ListView):
    model = Post
    ordering = '-pk'

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()

        # e-class 카테고리 자동 추가
        Category.objects.get_or_create(name='e-class', slug='e_class')

        assignment = Assignment.objects.all()
        quiz = Quiz.objects.all()

        category = get_object_or_404(Category, slug='e_class')

        try:
            for other in assignment:
                Post.objects.get_or_create(
                    title=str('[' + other.activity.lecture.name + ']') + other.title,
                    content=other.content,
                    deadline=other.due_date,
                    category=category,
                    author=self.request.user,
                )

            for other in quiz:
                Post.objects.get_or_create(
                    title=str('[' + other.activity.lecture.name + ']') + other.title,
                    content=other.questions,
                    deadline=other.due_date,
                    category=category,
                    author=self.request.user,
                )
        except Post.MultipleObjectsReturned:
            messages.warning(self.request, 'warning')
            context['messages'] = 'e-class 카테고리에서 중복되는 게시물이 존재합니다.'

        # 현재 날짜
        current_date = timezone.now().date()

        # 요일 설정
        dateDict = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}

        # 날짜 출력
        today_formatted = DateFormat(current_date).format('Y.m.d')
        context['today'] = today_formatted + ' (' + dateDict[current_date.weekday()] + ')'

        # 날짜 저장
        self.request.session['stored_date'] = current_date.strftime('%Y-%m-%d')

        # 작성자와 사용자가 같은 포스트, 데드 라인과 현재 날짜가 같은 포스트 불러오기 (홈에서는 무조건 현재 날짜)
        context['post_list_today'] = Post.objects.filter(deadline__date=current_date, author=self.request.user)

        # 카테고리 사용자 별로 포스트 세기
        all_categories = Category.objects.all()

        categories_post_counts = {}
        for category in all_categories:
            count = Post.objects.filter(category=category, author=self.request.user).count()
            categories_post_counts[category] = count

        context['categories_post_counts'] = categories_post_counts
        context['no_categories_post_count'] = Post.objects.filter(category=None, author=self.request.user).count()

        return context


def change_date(request, **kwargs):
    # 이전 날짜
    stored_date_str = request.session.get('stored_date', '')
    # 현재 날짜
    current_date = timezone.now().date()

    # 이전 버튼이 눌리면 날짜 하루 전으로, 다음 버튼이 눌리면 다음 날짜로 가기
    # 버튼이 눌리지 않았다면 현재 날짜 표시하기
    if 'prev' in request.GET:
        stored_date = timezone.datetime.strptime(stored_date_str, '%Y-%m-%d').date() - timedelta(days=1)
        request.session['stored_date'] = stored_date.strftime('%Y-%m-%d')
        stored_date_str = request.session['stored_date']
    elif 'next' in request.GET:
        stored_date = timezone.datetime.strptime(stored_date_str, '%Y-%m-%d').date() + timedelta(days=1)
        request.session['stored_date'] = stored_date.strftime('%Y-%m-%d')
        stored_date_str = request.session['stored_date']
    elif stored_date_str is None or stored_date_str == '' or ('prev' not in request.GET and 'next' not in request.GET):
        stored_date = current_date
        request.session['stored_date'] = stored_date.strftime('%Y-%m-%d')
        stored_date_str = request.session['stored_date']
    else:
        stored_date = timezone.datetime.strptime(stored_date_str, '%Y-%m-%d').date()

    # 요일 설정
    dateDict = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}

    # 날짜 출력
    today_formatted = DateFormat(stored_date).format('Y.m.d')
    today = today_formatted + ' (' + dateDict[stored_date.weekday()] + ')'

    # 날짜 저장
    post_list_today = Post.objects.filter(deadline__date=stored_date, author=request.user)

    # 카테고리
    all_categories = Category.objects.all()

    categories_post_counts = {}
    for category in all_categories:
        count = Post.objects.filter(category=category, author=request.user).count()
        categories_post_counts[category] = count

    no_categories_post_count = Post.objects.filter(category=None, author=request.user).count()

    return render(
        request,
        'home/post_list.html',
        {
            'post_list_today': post_list_today,
            'stored_date_str': stored_date_str,
            'today': today,
            'stored_date': stored_date.strftime('%Y-%m-%d'),
            'no_categories_post_count': no_categories_post_count,
            'categories_post_counts': categories_post_counts,
        }
    )


class CategoryList(ListView):
    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_categories_post_count'] = Post.objects.filter(category=None, author=self.request.user).count()
        context['categories_post_count'] = Post.objects.filter(category=self.category, author=self.request.user).count()
        return context


class PostDetail(DetailView):
    model = Post


def postCreate(request):
    if request.method == "POST":  # 데이터를 저장할 때
        form = PostForm(request.POST)
        if form.is_valid():
            post = Post()
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.deadline = form.cleaned_data['deadline']

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>HOME</title>

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
            rel="stylesheet"
        />
        <link
            href="{% static 'home/bootstrap/bootstrap.min.css' %}"
            rel="stylesheet"
            media="screen"
        />
        <script
            src="https://kit.fontawesome.com/726bbd6862.js"
            crossorigin="anonymous"
        ></script>
        <link
            href="{% static 'css/post_list.css' %}"
            rel="stylesheet"
            media="screen"
        />
        <link
            href="{% static 'css/login.css' %}"
            rel="stylesheet"
            media="screen"
        />
    </head>
    <body
        class="d-flex flex-column min-vh-100"
        style="
            background-color: #fffff4;
            color: #2d3142;
            font-family: 'Inter', sans-serif;
        "
    >
        <!-- NavBar -->
        {% include 'home/nav.html' %}

        <!-- 페이지 내용 작성-->
        <div class="container my-4">{% block main_area %} {% endblock %}</div>

        <!-- Footer -->
        {% include 'home/footer.html' %}


        <script
            src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

home/templates/home/category_list.html
{% extends 'home/base.html' %}
{% load static %}
{% block main_area %}
<div class="row mx-5">
    <div class="col-4 mt-3 mb-5">
        <div id="title" style="font-size: 50px">
            <div style="margin-bottom: -15px">Check</div>
            <div style="margin-bottom: -15px">Your</div>
            <div>
                Deadline<img
                    src="{% static 'img/home_notice.png' %}"
                    style="width: 40px; height: 40px; margin-left: 5px"
            />
            </div>
        </div>
        <div id="categoryBox" style="width: 250px">
            <div
                    id="categoryTitle"
                    style="width: 190px; margin: 30px 30px 20px 30px"
            >
                <p style="margin: 20px 0px 0px 0px">YOUR</p>
                <p style="margin: 0px 0px 20px 0px">CATEGORY</p>
            </div>
            <ul id="category" style="margin-bottom:20px">
                {% for category_c, count in categories_post_counts.items %}
                <li>
                    <a href="/home/category/{{ category_c.slug }}/" style="text-decoration: none; color: #2d3142">{{ category_c.name }} ({{ count }})</a>
                </li>
                {% endfor %}
                <li>
                    <a href="/home/category/no_category/" style="text-decoration: none; color: #2d3142">미분류 ({{ no_categories_post_count }})</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-8 mt-3 mb-5">
        <div class="listBox" style="position: relative;">
            <div class="controll">
                <div id="date" style="font-weight: 700;">{{ category }}</div>
            </div>
            <div class="todoBox">
                 {% if post_list.exists %}
                    {% for p in post_list %}
                    <form class="todo" style="margin-bottom:10px" method="post" action="{% if category == '미분류' %}{% url 'home:todo_check_no_category' pk=p.pk %}{% else %}{% url 'home:todo_check_category' pk=p.pk slug=category.slug %}{% endif %}">
                        {% csrf_token %}
                        <button type="submit" id="checkBtn" style="border: none; background: none; width: 40px; cursor: pointer; margin-right: 20px;">
                            {% if p.complete %}
                            <img src="{% static 'img/home_complete.png' %}" alt="Complete" id="todoIconCom"/>
                            {% else %}
                            <img src="{% static 'img/home_incom.png' %}" alt="InComplete" id="todoIconInCom"/>
                            {% endif %}
                        </button>
                        <a id="todoTitle" href="{{ p.get_absolute_url }}" style="text-decoration: none; color: #2D3142;">{{ p.title | truncatechars:8 }}</a>
                        <div id="todoDeadline">
                            {% if p.complete == False %}
                                {% if p.deadline|timeuntil|first == '0' %}
                                    (over {{ p.deadline|timesince }})
                                {% else %}
                                    ({{ p.deadline|timeuntil }})
                                {% endif %}
                                {% else %}
                                    <span style="color: #17DC1F;">(Done)</span>
                            {% endif %}
                        </div>
                    </form>
                    {% endfor %}
                {% else %}
                <div class="empty">
                    <div id="des">
                        <p style="margin: 0; text-align: center">ADD</p>
                        <p style="margin: 0; text-align: center">YOUR</p>
                        <p style="margin: 0; text-align: center">DEADLINE!</p>
                    </div>
                    <a id="add" href="/home/add_list/"
                    ><img
                            src="{% static 'img/home_add.png' %}"
                            style="width: 130px"
                    /></a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/popup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>popup</title>
</head>

<body style="background-color:#FFF7D3">
    <h>마감 기한이 얼마 남지 않은 <br> 일정이 있어요</h>
    <hr>

<!-- 알릴 내용 추가-->
    {% load static %}

    {% for item in post_content %}
        {% if item.is_deadline_today %}
            {{ item.title | truncatechars:6 }}
            <a style="text-align: right; color: red;">{{ item.deadline|timeuntil }} 남음</a>
            <br>
        {% endif %}
    {% endfor %}


</body>
</html>

home/templates/home/post_detail.html
{% extends 'home/base.html' %}
{% load static %}
{% block main_area %}

<div class="row my-2" style="font-size:50px;" xmlns="http://www.w3.org/1999/html">
        CHECK LIST DETAILS!
    </div>

    <div>
        <!--할 일 출력-->
        <div style="background-color: #FFF7D3; border-radius: 110px;" class="row my-2 py-5 col px-5 mx-5">
            <div class="row">
                <div class="col-md-1">
                    <div class="row my-1 py-3 col px-1">
                        <form method="post" action="{% url 'home:todo_check2' post.pk %}">
                            {% csrf_token %}
                                <button type="submit" id="checkBtn" style="border: none; background: none; width: 40px; cursor: pointer; margin-left: 10px;">
                                    {% if post.complete %}
                                        <img src="{% static 'img/home_complete.png' %}" alt="Complete" id="todoIconCom"/>
                                    {% else %}
                                        <img src="{% static 'img/home_incom.png' %}" alt="Complete" id="todoIconInCom"/>
                                    {% endif %}
                                </button>
                        </form>
                    </div>
                </div>
                <div class="col-md-8">
                    <div style="background-color: #FFFFF4; border: 3px solid #2D3142; border-radius: 50px; font-size:25px;" class="row py-3 col px-4">
                        <b>{{ post.title }}</b>
                    </div>
                    <div style="font-size:20px; height: 300px; width: 100%;" class="rounded-5 row mt-5 mb-2 py-1 col mx-5 px-1">
                        {{ post.content }}
                    </div>
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-1">
                    <div class="row pt-2 col pe-3">
                        <a href="{% url 'home:postDelete' post.id %}" role="button">
                            <img src="{% static 'img/delete_icon.png' %}" width="90%" height="90%" alt="delete">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="row my-2 col mx-5">
            <!--마감 기한 출력-->
            <div class="col-md-8">
                <div style="background-color: #FFEC9D; border: 8px solid #FFEC9D; border-radius: 50px; font-size:20px;" class="row pt-3 col px-5">
                    <p><b><span style="color: #E71D36">DeadLine:&nbsp;&nbsp;</span>{{ post.deadline.year }}년 {{ post.deadline.month }}월 {{ post.deadline.day }}일&nbsp;&nbsp;{{ post.deadline.hour }}시 {{ post.deadline.minute }}분까지</b>
                        <span style="color:gray; text-align:end;">(24시간 단위)</span></p>
                    <!--  {{ post.deadline.second }}초 -->
                </div>
            </div>

            <div class="col-md-1"></div>


            <!--버튼-->
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-6">
                        <a href="../edit_list_{{ post.pk }}/" style="text-decoration: none;">
                            <div style="background-color: #2D3142; border:5px solid #2D3142; border-radius: 50px;" class="col ms-3">
                                <input style="background-color: #2D3142; text-align:center; font-size: 30px; color: #FFFFFF; border-radius: 50px;" type="button" id="edit" class="form-control border-0" value="EDIT">
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a href="../" style="text-decoration: none;">
                            <div style="background-color: #FFFFF4; border: 5px solid #2D3142; border-radius: 50px;" class="col ms-3">
                                <input style="background-color: #FFFFF4; text-align:center; font-size: 30px; color: #2D3142; border-radius: 50px;" type="button" id="exit" class="form-control border-0" value="EXIT">
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

home/templates/home/post_list.html
{% extends 'home/base.html' %}
{% load static %}
{% block main_area %}

{% if "e-class 카테고리에서 중복되는 게시물이 존재합니다." in messages %}
    <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="messageModalLabel">알림</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div id="messageContent">{{ messages }}</div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div class="row mx-5">
    <div class="col-4 mt-3 mb-5">
        <div id="title" style="font-size: 50px">
            <div style="margin-bottom: -15px">Check</div>
            <div style="margin-bottom: -15px">Your</div>
            <div>
                Deadline<img
                    src="{% static 'img/home_notice.png' %}"
                    style="width: 40px; height: 40px; margin-left: 5px"
            />
            </div>
        </div>
        <div id="categoryBox" style="width: 250px">
            <div
                    id="categoryTitle"
                    style="width: 190px; margin: 30px 30px 20px 30px"
            >
                <p style="margin: 20px 0px 0px 0px">YOUR</p>
                <p style="margin: 0px 0px 20px 0px">CATEGORY</p>
            </div>
            <ul id="category" style="margin-bottom:20px">
                {% for category, count in categories_post_counts.items %}
                <li>
                    <a href="/home/category/{{ category.slug }}/" style="text-decoration: none; color: #2d3142">{{ category.name }} ({{ count }})</a>
                </li>
                {% endfor %}
                <li>
                    <a href="/home/category/no_category/" style="text-decoration: none; color: #2d3142">미분류 ({{ no_categories_post_count }})</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-8 mt-3 mb-5">
        <div class="listBox" style="position: relative;">
            <form class="controll" method="get" action="{% url 'home:change_date' %}">
                {% csrf_token %}
                <button id="before" name="prev" type="submit" style="border: none; background: none;">
                    <img src="{% static 'img/home_before.png' %}" style="width: 40px"/>
                </button>
                <div id="date" style="font-weight: 700;">{{ today }}</div>
                <button id="after" name="next" type="submit" style="border: none; background: none;">
                    <img src="{% static 'img/home_after.png' %}" style="width: 40px"/>
                </button>
                <input type="hidden" name="date" value="{{ stored_date }}">
            </form>
            <div class="todoBox">
                 {% if post_list_today.exists %}
                    {% for p in post_list_today %}
                    <form class="todo" style="margin-bottom:10px" method="post" action="{% url 'home:todo_check' pk=p.pk %}">
                        {% csrf_token %}
                        <button type="submit" id="checkBtn" style="border: none; background: none; width: 40px; cursor: pointer; margin-right: 20px;">
                            {% if p.complete %}
                            <img src="{% static 'img/home_complete.png' %}" alt="Complete" id="todoIconCom"/>
                            {% else %}
                            <img src="{% static 'img/home_incom.png' %}" alt="InComplete" id="todoIconInCom"/>
                            {% endif %}
                        </button>
                        <a id="todoTitle" href="{{ p.get_absolute_url }}" style="text-decoration: none; color: #2D3142;">{{ p.title | truncatechars:8 }}</a>
                        <div id="todoDeadline">
                            {% if p.complete == False %}
                                {% if p.deadline|timeuntil|first == '0' %}
                                    (over {{ p.deadline|timesince }})
                                {% else %}
                                    ({{ p.deadline|timeuntil }})
                                {% endif %}
                                {% else %}
                                    <span style="color: #17DC1F;">(Done)</span>
                            {% endif %}
                        </div>
                    </form>
                    {% endfor %}
                {% else %}
                <div class="empty">
                    <div id="des">
                        <p style="margin: 0; text-align: center">ADD</p>
                        <p style="margin: 0; text-align: center">YOUR</p>
                        <p style="margin: 0; text-align: center">DEADLINE!</p>
                    </div>
                    <a id="add" href="/home/add_list/"
                    ><img
                            src="{% static 'img/home_add.png' %}"
                            style="width: 130px"
                    /></a>
                </div>
                {% endif %}
            </div>
            <a id="small_add" href="/home/add_list/" style="position: absolute; right: 60px; bottom: 30px; width: 40px;">
                    <img src="{% static 'img/home_add.png' %}" style="width: 40px"/>
            </a>
        </div>
    </div>
</div>


    <!-- 팝업창 띄우기-->
    <script language="javascript">

             window.open("/home/popup","팝업 이름","width=300,height=300, left=300, top=300");

    </script>
<script>
      document.addEventListener('DOMContentLoaded', function() {
          var messageModal = new bootstrap.Modal(document.getElementById('messageModal'));

          var messages = "{{ messages }}";
          if (messages) {
              document.getElementById('messageContent').innerHTML = messages;
              messageModal.show();
      }

      var closeButton = document.querySelector('#messageModal .btn-close');
          closeButton.addEventListener('click', function() {
              messageModal.hide();
          });
      });
</script>
{% endblock %}