eclass/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lecture_list, name='lecture_list'),
    path('lecture/<int:lecture_id>/', views.lecture_detail, name='lecture_detail'),
    path('activity/<int:activity_id>/', views.activity_detail, name='activity_detail'),
    path('assignment/create/<int:activity_id>/', views.assignment_creation, name='assignment_create'),
    path('quiz/create/<int:activity_id>/', views.quiz_creation, name='quiz_create'),
]

home/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'home'

urlpatterns = [
    path('delete_<int:pk>/', views.postDelete, name='postDelete'),
    path('edit_list_<int:pk>/', views.postEdit, name='postEdit'),
    path('add_list/', views.postCreate, name='postCreate'),
    path('check_details_<int:pk>/', views.PostDetail.as_view()),

    # 메인
    path('', views.PostList.as_view(), name='post_list'),
    # 카테고리 별
    path('category/<str:slug>/', views.category_page, name='category'),
    # 컴플리트(메인)
    path('todo_check/<int:pk>/', views.todo_check, name='todo_check'),
    # 컴플리트(카테고리)
    path('category/<str:slug>/todo_check_category/<int:pk>/', views.todo_check_category, name='todo_check_category'),
    path('category/no_category/<int:pk>/', views.todo_check_no_category, name='todo_check_no_category'),
    # 날짜 넘기기
    path('change_date/', views.change_date, name='change_date'),
    # 컴플리트(상세확인)
    path('todo_check2/<int:pk>/', views.todo_check2, name='todo_check2'),

    # 마이
    path('my/', views.my),

    # 팝업창
    path('popup/', views.popup),

    ]

toDD_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('eclass/', include('eclass.urls')),
    path('alarm/', include('alarm.urls')),
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eclass/models.py
from django.db import models

class Lecture(models.Model):
    name = models.CharField(max_length=100)
    professor = models.CharField(max_length=30)

class Activity(models.Model):
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    week = models.IntegerField()
    title = models.CharField(max_length=50)

class Assignment(models.Model):
    title = models.CharField(max_length=200)
    due_date = models.DateTimeField()
    content = models.TextField()
    activity = models.ForeignKey('Activity', on_delete=models.CASCADE)

class Quiz(models.Model):
    title = models.CharField(max_length=200)
    due_date = models.DateTimeField()
    questions = models.TextField()
    activity = models.ForeignKey('Activity', on_delete=models.CASCADE)

eclass/forms.py
from django import forms
from .models import Assignment, Quiz

class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['title', 'content', 'due_date']
        labels = {
            'title': '제목',
            'content': '내용',
            'due_date': '마감 일시',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': '제목 작성',
                }),
            'content': forms.Textarea(
                attrs={
                    'class': 'custom-textarea',
                    'placeholder': '내용 작성'
                }),
            'due_date': forms.DateTimeInput(
                attrs={
                    'class': 'custom-due-date',
                    'type': 'datetime-local',
                }),
        }

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['title', 'due_date', 'questions']
        labels = {
            'title': '제목',
            'questions': '문제',
            'due_date': '마감 일시',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': '제목 작성',
                }),
            'questions': forms.Textarea(
                attrs={
                    'class': 'custom-textarea',
                    'placeholder': '문제 출시'
                }),
            'due_date': forms.DateTimeInput(
                attrs={
                    'class': 'custom-due-date',
                    'type': 'datetime-local',
                }),
        }

eclass/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Lecture, Activity, Assignment, Quiz
from .forms import AssignmentForm, QuizForm

def lecture_list(request):
    lectures = Lecture.objects.all()
    return render(request, 'lecture_list.html', {'lectures': lectures})

def lecture_detail(request, lecture_id):
    lecture = Lecture.objects.get(pk=lecture_id)
    activities = Activity.objects.filter(lecture=lecture)
    return render(request, 'lecture_detail.html', {'lecture': lecture, 'activities': activities})

def activity_detail(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    return render(request, 'activity_detail.html', {'activity': activity})

def assignment_creation(request, activity_id):
    activity = Activity.objects.get(pk=activity_id)

    if request.method == 'POST':
        form = AssignmentForm(request.POST)
        if form.is_valid():
            assignment = Assignment()
            assignment.title = form.cleaned_data['title']
            assignment.content = form.cleaned_data['content']
            assignment.due_date = form.cleaned_data['due_date']
            assignment.activity = activity
            assignment.save()
            return redirect('lecture_detail', lecture_id=activity.lecture.id)
    else:
        form = AssignmentForm()

    return render(request, 'assignment_creation.html', {'form': form, 'activity': activity})


def quiz_creation(request, activity_id):
    activity = Activity.objects.get(pk=activity_id)

    if request.method == 'POST':
        form = QuizForm(request.POST)
        if form.is_valid():
            quiz = Quiz()
            quiz.title = form.cleaned_data['title']
            quiz.questions = form.cleaned_data['questions']
            quiz.due_date = form.cleaned_data['due_date']
            quiz.activity = activity
            quiz.save()
            return redirect('lecture_detail', lecture_id=activity.lecture.id)
    else:
        form = QuizForm()

    return render(request, 'quiz_creation.html', {'form': form, 'activity':activity})

eclass/templates/activity_detail.html
<!-- activity_detail.html -->

{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<link rel="stylesheet" type="text/css" href="{% static 'css/activity_detail_styles.css' %}">
<div class="container my-4">
  <div>
    <div class="main-title-container">
      <h4 class="main-title">학습 활동 추가</h4>
    </div>
    <div class="sub-title-container">
      <h5 class="sub-title">학습 활동</h5>
      <div class="icon-button">
        <a href="{% url 'assignment_create' activity.id %}" class="btn btn-secondary">
          <span class="icon">
            <img src="{% static 'img/assignment.png' %}" alt="Icon">
          </span>
          과제
        </a>
      </div>
      <div class="icon-button">
        <a href="{% url 'quiz_create' activity.id %}" class="btn btn-secondary">
          <span class="icon">
            <img src="{% static 'img/quiz.png' %}" alt="Icon">
          </span>
          퀴즈
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

eclass/templates/assignment_creation.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<link rel="stylesheet" type="text/css" href="{% static 'css/creation_styles.css' %}">

<div class="container my-4">
  <h2 class="body-title">과제</h2>
    <form method="post">
        {% csrf_token %}
        <div class="assignment-fields">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>
        <div class="assignment-fields">
            {{ form.content.label_tag }}
            {{ form.content }}
        </div>
        <h2 class="body-title">제출 기한 설정</h2>
        <div class="assignment-fields">
            {{ form.due_date.label_tag }}
            {{ form.due_date }}
        </div>
        <button type="submit">저장</button>
    </form>
</div>
{% endblock %}

eclass/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block head_title %}덕성여자대학교 e-Class{% endblock %}</title>
  <link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen"></link>
  <script src="https://kit.fontawesome.com/54c8fd0744.js" crossorigin="anonymous"></script>
</head>
<body>

  {% include 'nav.html' %}
      {% block main_area %}
      {% endblock %}
  {% include 'footer.html' %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

eclass/templates/footer.html
<!-- footer.html -->

<footer class="py-4 mt-auto" style="background-color: #2d3142; color: #fffff4; text-align: center; position: fixed; bottom: 0; width: 100%;">
    <div class="container">
        <p class="m-0">
            [01369] 서울특별시 도봉구 삼양로 144길 33 (ARS)02-901-8000 / e-Class 문의 : 02-901-8696
        </p>
    </div>
</footer>

eclass/templates/lecture_detail.html
<!-- lecture_detail.html -->

{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lecture_detail_styles.css' %}">

<div class="header-box" style="background: url('{% static 'img/pattern.png' %}') repeat">
  <img id="profile" src="{% static 'img/profile.png' %}" alt="Profile Image">
  <div>
    <p class="name">{{ lecture.name }}</p>
    <p class="professor">{{ lecture.professor }}</p>
  </div>
</div>

<div class="container my-4">
  <h6>주차 별 학습 활동</h6>
  <div class="activity-list">
    {% for activity in lecture.activity_set.all %}
      <div class="activity-box">
        <p class="activity-title">{{ activity.title }}</p>
        <ul style="list-style-type: none;">
          {% for assignment in activity.assignment_set.all %}
          <li><b>과제:</b> {{ assignment.title }}</li>
          {% endfor %}
          {% for quiz in activity.quiz_set.all %}
          <li><b>퀴즈:</b> {{ quiz.title }}</li>
          {% endfor %}
        </ul>
        <div class="add-activity">
          <a href="{% url 'activity_detail' activity.id %}" class="btn btn-success">+ 활동 추가</a>
        </div>
      </div>
    <hr>
    {% endfor %}
  </div>
</div>
{% endblock %}

eclass/templates/lecture_list.html
<!-- lecture_list.html -->

{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lecture_list_styles.css' %}">
<div class="container my-4">
  <h4>강좌 전체보기</h4>
  <ul>
    {% for lecture in lectures %}
      <li>
        <a href="{% url 'lecture_detail' lecture.id %}">
          <img id="profile" src="{% static 'img/profile.png' %}" alt="Profile Image">
          <img id="lect" src="{% static 'img/lect.png' %}" alt="lecture Image">
          <div>
            <p>{{ lecture.name }}</p>
            <p>{{ lecture.professor }}</p>
          </div>
        </a>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

eclass/templates/nav.html
<!-- nav.html -->

<nav class="navbar navbar-expand-lg navbar-dark"
     style="background-color: #1E5BAA; min-height: 70px;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'lecture_list' %}">덕성여자대학교 e-Class</a>
    <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
      <a class="nav-link" href="#" style="margin-right: 10px;">홈</a>
      <a class="nav-link" href="#" style="margin-right: 10px;">강의실</a>
      <a class="nav-link" href="#" style="margin-right: 10px;">일정</a>
      <!-- 추가적인 메뉴 항목들을 필요에 따라 추가 -->
    </div>
  </div>
</nav>

eclass/templates/quiz_creation.html
{% extends 'base.html' %}
{% load static %}
{% block main_area %}
<link rel="stylesheet" type="text/css" href="{% static 'css/creation_styles.css' %}">

<div class="container my-4">
  <h2 class="body-title">퀴즈</h2>
    <form method="post">
        {% csrf_token %}
        <div class="assignment-fields">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>
        <div class="assignment-fields">
            {{ form.questions.label_tag }}
            {{ form.questions }}
        </div>
        <h2 class="body-title">제출 기한 설정</h2>
        <div class="assignment-fields">
            {{ form.due_date.label_tag }}
            {{ form.due_date }}
        </div>
        <button type="submit">저장</button>
    </form>
</div>
{% endblock %}